CREATE TABLE MEMBERS (
	EMAIL VARCHAR(255) NOT NULL,
	EMAILHASH VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(40) NOT NULL,
	NICKNAME VARCHAR(25) NOT NULL UNIQUE,
	ADMIN SMALLINT,
	BANNED SMALLINT,
	PRIMARY KEY (EMAIL)
);

CREATE TABLE BOARDS (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	NAME VARCHAR(255) NOT NULL,
	TOPICSCOUNT INTEGER,
	PRIMARY KEY (ID)
);

CREATE TABLE OPERATORS (
	BOARD INTEGER NOT NULL,
	MEMBER VARCHAR(255) NOT NULL,
	PRIMARY KEY (BOARD, MEMBER),
	FOREIGN KEY (BOARD) REFERENCES BOARDS(ID),
	FOREIGN KEY (MEMBER) REFERENCES MEMBERS(EMAIL)
);

CREATE TABLE TOPICS (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	TITLE VARCHAR(255) NOT NULL,
	POSTSCOUNT INTEGER,
	CREATOR VARCHAR(255) NOT NULL,
	BOARDID INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (CREATOR) REFERENCES MEMBERS(EMAIL),
	FOREIGN KEY (BOARDID) REFERENCES BOARDS(ID)
);

CREATE TABLE POSTS (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
	CREATOR VARCHAR(255) NOT NULL,
	CONTENT VARCHAR(2000) NOT NULL,
	CREATED TIMESTAMP NOT NULL,
	TOPICID INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (CREATOR) REFERENCES MEMBERS(EMAIL),
	FOREIGN KEY (TOPICID) REFERENCES TOPICS(ID)
);
